- name: checkout dotfiles
  git:
    repo: https://github.com/katsuhisa91/dotfiles.git
    dest: ~/workspace/settings/dotfiles

- name: Run 'setup' target as root
  make:
    chdir: ~/workspace/settings/dotfiles
    target: setup
  become: yes